/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"


void
dateprog_1(char *host)
{
	CLIENT *clnt;
	long  *result_1;
	char *binddate_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DATEPROG, PROGVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = binddate_1((void*)&binddate_1_arg, clnt);
	if (result_1 == (long *) NULL) {
		clnt_perror (clnt, "call failed");
	}
    else 
    {
         printf("time on host %s is %ld \n",host,*result_1);

     }
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	dateprog_1 (host);
exit (0);
}
