/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arraysum.h"

int *
sum_function_1_svc(mystruct *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	int size=argp->n;
    for(int i=0;i<size;i++)
    {
    	result+=(argp->a1[i]+argp->a2[i]);    
    	
    }
	return &result;
}
