/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arraysum.h"


void
arraysumprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	mystruct  sum_function_1_arg;
   
    int n,a;
    printf("Enter number of elements\n");
    scanf("%d",&n);
    sum_function_1_arg.n=n;
    printf("Enter array1 elements\n");
    for(int i=0;i<n;i++)
    {
      scanf("%d",&a);
      sum_function_1_arg.a1[i]=a;
    }
    printf("Enter array2 elements\n");
    for(int i=0;i<n;i++)
    {
       scanf("%d",&a);
       sum_function_1_arg.a2[i]=a;
    }

#ifndef	DEBUG
	clnt = clnt_create (host, ARRAYSUMPROG, PROGVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_function_1(&sum_function_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else 
	{
		printf("Rusult = %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	arraysumprog_1 (host);
exit (0);
}
